<div class="container">
    <h1>My Bae is <?php echo $this->bae; ?></h1>
    <h2>Portfolios</h2>

    <?php foreach ( $this->portfolios as $portfolio): ?>
        <div class="portfolio">
            <strong>Owner:</strong> <?php echo $portfolio->getOwner(); ?><br>
            <strong>Pieces #:</strong> <?php echo $portfolio->getPieces(); ?><br>
            <strong>Medium:</strong> <?php echo $portfolio->getMedium(); ?><br>
            <em>Favorite Artist: </em> <?php echo $portfolio->getFavoriteArtist(); ?>   
        </div>
    <?php endforeach; ?>

    <p id="josh"> An organized and easy to access protfolio is key for any deisgner or artist. </p>
    <p id="josh"> Using this service, you can upload your portfolio and give anyone specific access to it. </p>
    <p id="josh"> Your portfolio can also be protected from random views.  If they dont have permission from you, they can't see it. </p>
    <p id="josh"> This website also serves as a job request host.  Look up the kind of work you want done and a list of artists will appear for you. </p>
    <p id="josh"> You can then request their portfolios or send in job descriptions and find the person who is right for your job. </p>    
    <p id="josh"> Click here to sign up and get started!
    <p id="josh"> Already a member? Click here.
</div>